version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: minha_api_books
      POSTGRES_USER: allan
      POSTGRES_PASSWORD: agripa99
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    image: arcanjus3/minha-api:latest
    depends_on:
      - db
    environment:
      DB_URL: postgres://allan:agripa99@db:5432/minha_api_books?sslmode=disable
    ports:
      - "8080:8080"

volumes:
  pgdata: