services:
  books_db:
    image: postgres:16
    #container_name: books_db
    #restart: always
    environment:
      POSTGRES_DB: minha_api_books
      POSTGRES_USER: allan
      POSTGRES_PASSWORD: agripa99
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books_network

  api:
    build: .
    depends_on:
      - books_db
    #container_name: books_api
    restart: always
    environment:
      DB_URL: postgres://allan:agripa99@books_db:5432/minha_api_books?sslmode=disable
    ports:
      - "8080:8080"
    networks:
      - books_network

networks:
  books_network:
