services:
  books_db:
    image: postgres:16
    environment:
      POSTGRES_DB: minha_api_books
      POSTGRES_USER: allan
      POSTGRES_PASSWORD: agripa99
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - books_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U allan -d minha_api_books"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      books_db:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=1
      - DB_URL=postgres://allan:agripa99@books_db:5432/minha_api_books?sslmode=disable
    ports:
      - "5000:5000" # alterado para alinhar com a porta do servidor Go
    networks:
      - books_network

networks:
  books_network: